name: Deploy

on:
  push:
    branches: 
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::464108382357:role/InfraStack-GithubOicdBackendRole8A101E36-TcMTmu673ZOi
          aws-region: eu-central-1

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and push img
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --platform linux/amd64 -t $ECR_REGISTRY/backend-images:latest .
          docker push $ECR_REGISTRY/backend-images:latest
        